### ISSUE TITLE
Unreadable in Chrome "dark-mode" 

### ISSUE THREAD

**Issue by benwinding** [slowernews/slowernews#5]
Using chrome with the dark-mode flag enabled. I've never seen any other site do this, could be worth checking out as dark-mode is becoming more popular. 

![Screenshot_20200313-144418_Chrome](https://user-images.githubusercontent.com/11782590/76589211-3aaa4500-6539-11ea-9b49-5751578d19b2.jpg)

**Comment by slowernews** [comment]
This issue is related with issue #2 that was solved by @itsrainingmani . Maybe he can help here also if he finds some spare time.

**Comment by itsrainingmani** [comment]
So that PR doesn't address the issue perfectly since the `prefers-color-scheme` media query detects if the OS has a preference, not the browser like I'd assumed.

There are a couple of workarounds - 

* Change the background color of the page to be dark if the OS prefers dark mode.
* Try to detect if the user is navigating from a mobile browser and using dark mode and then changing the text-shadow color.

However, neither of those are perfect. It doesn't seem like there's really an easy fix for this issue.

**Comment by slowernews** [comment]
Hello! I merged a pull request (#10) adressing this issue and, AFAIK, it should work now. Could you test it? @itsrainingmani @benwinding 

Thanks!

(edit:  I've tested and looks great on Safari/IOS but it still looks blurry on Chrome/Win7 with dark-mode flag enabled. @nkoehring)

**Comment by slowernews** [comment]
Fixed!
